Repository savio81/cpp_update, pull requests merged in 2022-10, with the labels that each got.

#9 updated #1
  python
Labels: duplicate, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#10 interpret and edit #2
  nexas
Labels: help wanted, invalid, question, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#12 bug fix #3
  python
Labels: bug, documentation, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#14 fixed bug in code #5
  path
Labels: bug, documentation, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#15 added new code
  hello world
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#18 Update hello world also edit
  hello world
Labels: bug, documentation, duplicate, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag

#17 bug resolved #7
  path
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-swag
